/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#00201e",
        "outline": "#8b9291",
        "secondary-fixed": "#ffe088",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "tertiary-fixed": "#e7e2d8",
        "outline-variant": "#414847",
        "tertiary-container": "#312f29",
        "tertiary-fixed-dim": "#cac6bd",
        "surface-tint": "#a7cec9",
        "background": "#120B06",
        "inverse-surface": "#c1ebe6",
        "inverse-on-surface": "#0c3634",
        "on-surface": "#c1ebe6",
        "on-background": "#c1ebe6",
        "tertiary": "#cac6bd",
        "surface": "#1B0F08",
        "surface-bright": "#2A160A",
        "primary-container": "#2A160A",
        "surface-variant": "#3A2518",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#2A160A",
        "on-primary-container": "#789e9a",
        "on-tertiary-fixed": "#1d1c16",
        "error-container": "#93000a",
        "secondary": "#D39A53",
        "on-tertiary-fixed-variant": "#494740",
        "surface-container": "#1B0F08",
        "surface-container-highest": "#3A2518",
        "primary-fixed": "#c2eae5",
        "secondary-container": "#af8d11",
        "inverse-primary": "#406561",
        "on-surface-variant": "#c0c8c6",
        "surface-container-lowest": "#120B06",
        "on-tertiary": "#32302a",
        "on-primary-fixed": "#00201e",
        "on-primary": "#0e3633",
        "primary": "#a7cec9",
        "on-primary-fixed-variant": "#284d4a",
        "accent-gold": "#FFF8EF",
        "accent-gold-border": "#E6D3BB",
        "sunset-teal": "#120B06",
        "sunset-gold": "#D39A53",
        "sunset-teal-2": "#1B0F08",
        "sunset-gold-2": "#E4B875",
        "sunset-gold-light": "#F3D7A8",
        "sunset-bg": "#F7EFE4",
        "sunset-teal-3": "#2A160A",
        "sunset-gold-3": "#C7833E",
        "sunset-beige-3": "#FFF8EF",
        "sunset-border-3": "#E6D3BB",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px",
      },
      spacing: {
        "unit": "8px",
        "container-margin": "24px",
        "gutter": "16px",
        "section-gap": "64px",
      },
      fontFamily: {
        serif: ['"Playfair Display"', 'serif'],
        sans: ['Inter', '"Plus Jakarta Sans"', 'sans-serif'],
        "display-lg": ['"Playfair Display"'],
        "body-md": ['"Plus Jakarta Sans"'],
        "body-lg": ['"Plus Jakarta Sans"'],
        "label-sm": ['"Plus Jakarta Sans"'],
        "headline-lg-mobile": ['"Playfair Display"'],
        "headline-lg": ['"Playfair Display"'],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["14px", { letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
